export interface PathLesson {
  id: string;
  title: string;
  description: string;
  content: string;
  codeExample: string;
  order: number;
}

export interface SpecializationPath {
  id: string;
  name: string;
  icon: string;
  color: string;
  language: "python" | "javascript";
  description: string;
  lessons: PathLesson[];
  capstoneTitle: string;
  capstoneDescription: string;
  capstoneRequirements: string[];
  certificateName: string;
}

function generateLessons(pathId: string, topics: [string, string][], language: string): PathLesson[] {
  return topics.map(([title, desc], i) => ({
    id: `${pathId}-${i + 1}`,
    title,
    description: desc,
    order: i + 1,
    content: `## ${title}\n\nThis lesson covers ${title.toLowerCase()} in depth.\n\n**What you'll learn:**\n- Core concepts of ${title.toLowerCase()}\n- Best practices and real-world patterns\n- Hands-on coding exercises\n\n**${desc}**`,
    codeExample: `// ${title}\n// ${language === "python" ? "Python" : "JavaScript"} example\n\nconsole.log("Lesson ${i + 1}: ${title}");`,
  }));
}

// ==================== WEB DESIGNER (100 lessons) ====================
const webDesignTopics: [string, string][] = [
  ["HTML Document Structure", "Build proper HTML5 documents from scratch."],
  ["Semantic HTML Elements", "Use header, nav, main, article, section, footer."],
  ["HTML Forms & Inputs", "Build interactive forms with validation."],
  ["HTML Tables & Lists", "Display structured data with tables and lists."],
  ["HTML Media Elements", "Embed images, video, audio, and iframes."],
  ["HTML Accessibility (a11y)", "Make websites usable for everyone."],
  ["CSS Selectors & Specificity", "Target elements precisely with selectors."],
  ["CSS Box Model", "Master margin, padding, border, and content."],
  ["CSS Colors & Typography", "Style text with fonts, colors, and spacing."],
  ["CSS Display & Positioning", "Control layout with display, position, float."],
  ["CSS Flexbox Basics", "One-dimensional layouts with flexbox."],
  ["CSS Flexbox Advanced", "Complex flex layouts and alignment."],
  ["CSS Grid Basics", "Two-dimensional layouts with CSS Grid."],
  ["CSS Grid Advanced", "Named areas, auto-fit, and complex grids."],
  ["CSS Responsive Design", "Media queries and mobile-first approach."],
  ["CSS Units & Variables", "rem, em, vh, vw and CSS custom properties."],
  ["CSS Transitions", "Smooth state changes with transitions."],
  ["CSS Animations & Keyframes", "Complex motion with @keyframes."],
  ["CSS Transforms", "Scale, rotate, translate, and skew elements."],
  ["CSS Pseudo-classes & Elements", "Style states and generated content."],
  ["CSS Gradients & Backgrounds", "Linear, radial gradients and bg images."],
  ["CSS Shadows & Filters", "Box-shadow, text-shadow, and CSS filters."],
  ["CSS Clipping & Masking", "Clip-path and mask for creative shapes."],
  ["CSS Container Queries", "Responsive components based on parent size."],
  ["Tailwind CSS Setup", "Install and configure Tailwind CSS."],
  ["Tailwind Utility Classes", "Style elements with utility-first approach."],
  ["Tailwind Responsive Design", "Responsive prefixes: sm, md, lg, xl."],
  ["Tailwind Components", "Build reusable components with Tailwind."],
  ["Tailwind Custom Configuration", "Extend theme, colors, fonts, spacing."],
  ["Tailwind Animations & Plugins", "Add motion and extend Tailwind."],
  ["Design Principles", "Balance, contrast, hierarchy, whitespace."],
  ["Color Theory", "Color wheels, palettes, and psychology."],
  ["Typography Design", "Font pairing, scales, and readability."],
  ["Layout Patterns", "Common web layouts and when to use them."],
  ["Design Systems", "Build consistent token-based design systems."],
  ["Wireframing & Prototyping", "Plan designs before coding."],
  ["Figma for Developers", "Use Figma to extract design specs."],
  ["UI Component Library", "Build buttons, cards, modals, dropdowns."],
  ["Navigation Patterns", "Navbars, sidebars, breadcrumbs, tabs."],
  ["Form Design & UX", "Design forms that users love to fill."],
  ["React Basics for Design", "Components, JSX, and rendering."],
  ["React Props & Children", "Pass data between components."],
  ["React State (useState)", "Add interactivity with state."],
  ["React Effects (useEffect)", "Side effects and data fetching."],
  ["React Event Handling", "Handle clicks, inputs, and forms."],
  ["React Lists & Conditional Rendering", "Map arrays and show/hide elements."],
  ["React Component Patterns", "Container, presentational, compound."],
  ["React Context for Theming", "Global state for dark/light mode."],
  ["React Hooks Deep Dive", "useRef, useMemo, useCallback."],
  ["React Custom Hooks", "Extract and reuse logic."],
  ["Next.js Pages & Routing", "File-based routing with Next.js."],
  ["Next.js Layouts & Templates", "Shared layouts and nested routes."],
  ["Next.js Data Fetching", "Server components and data loading."],
  ["Next.js API Routes", "Build backend endpoints."],
  ["Next.js Image & Font Optimization", "Optimize assets automatically."],
  ["Next.js Static & Dynamic Rendering", "SSG, SSR, and ISR."],
  ["SVG Graphics", "Create and animate SVGs."],
  ["Canvas API Basics", "Draw graphics with JavaScript."],
  ["CSS Art & Illustrations", "Create art with pure CSS."],
  ["Scroll Animations", "Animate elements on scroll."],
  ["Page Transitions", "Smooth transitions between pages."],
  ["Loading States & Skeletons", "Design loading experiences."],
  ["Error States & Empty States", "Design for when things go wrong."],
  ["Toast Notifications", "Build notification components."],
  ["Modal & Dialog Design", "Accessible modal patterns."],
  ["Drag & Drop Interfaces", "Build drag and drop UIs."],
  ["Infinite Scroll & Pagination", "Handle large lists of content."],
  ["Data Visualization Basics", "Charts and graphs with CSS/JS."],
  ["Dashboard Design", "Build data-rich dashboards."],
  ["E-commerce UI", "Product cards, cart, checkout flow."],
  ["Blog & Content UI", "Article layouts, reading experience."],
  ["Social Media UI", "Feed, profiles, and interactions."],
  ["Landing Page Design", "High-converting landing pages."],
  ["Portfolio Design", "Showcase your work effectively."],
  ["Email Template Design", "HTML emails that work everywhere."],
  ["Print & PDF Styling", "Style content for printing."],
  ["Cross-Browser Compatibility", "Make designs work everywhere."],
  ["CSS Performance", "Optimize CSS for speed."],
  ["Web Fonts Performance", "Load fonts without blocking render."],
  ["Image Optimization", "Responsive images, lazy loading, WebP."],
  ["Core Web Vitals", "LCP, FID, CLS optimization."],
  ["SEO for Designers", "Meta tags, Open Graph, structured data."],
  ["Dark Mode Implementation", "System and manual dark mode."],
  ["Internationalization (i18n)", "Multi-language support for UIs."],
  ["Micro-Interactions", "Small delightful animations."],
  ["Motion Design Principles", "When and how to animate."],
  ["Advanced Tailwind Patterns", "Group, peer, arbitrary values."],
  ["Component Testing", "Test UI components visually."],
  ["Storybook for Components", "Document and test components."],
  ["Design Handoff", "Developer-designer collaboration."],
  ["CSS Architecture (BEM, ITCSS)", "Organize large CSS codebases."],
  ["Accessibility Auditing", "Test and fix accessibility issues."],
  ["Progressive Web Apps (PWA)", "Installable web apps."],
  ["Web Performance Auditing", "Lighthouse and performance tools."],
  ["Deployment & CI/CD", "Deploy with Vercel, Netlify."],
  ["Version Control for Designers", "Git workflow for design files."],
  ["Client Communication", "Present designs to stakeholders."],
  ["Freelance Web Design", "Pricing, contracts, and client work."],
  ["Portfolio Project: Complete Website", "Build your best portfolio piece."],
  ["Career: Landing a Design Job", "Resume, portfolio, and interviews."],
];

// ==================== AI & ML (100 lessons) ====================
const aiTopics: [string, string][] = [
  ["What is Artificial Intelligence?", "Understanding AI, ML, and deep learning."],
  ["Python for Data Science", "NumPy, arrays, and numerical computing."],
  ["Pandas DataFrames", "Load, filter, and analyze structured data."],
  ["Data Visualization with Matplotlib", "Create charts, plots, and graphs."],
  ["Statistics Fundamentals", "Mean, median, standard deviation, distributions."],
  ["Probability Theory", "Probability rules, Bayes theorem."],
  ["Data Preprocessing", "Handle missing data, encoding, normalization."],
  ["Feature Engineering", "Create meaningful features from raw data."],
  ["Exploratory Data Analysis (EDA)", "Discover patterns before modeling."],
  ["Train/Test Split & Validation", "Evaluate models properly."],
  ["Linear Regression", "Predict continuous values."],
  ["Polynomial Regression", "Model non-linear relationships."],
  ["Logistic Regression", "Binary classification fundamentals."],
  ["Decision Trees", "Tree-based classification and regression."],
  ["Random Forests", "Ensemble learning with multiple trees."],
  ["Gradient Boosting (XGBoost)", "State-of-the-art tabular ML."],
  ["K-Nearest Neighbors", "Instance-based classification."],
  ["Support Vector Machines", "Maximum margin classifiers."],
  ["Naive Bayes", "Probabilistic text classification."],
  ["K-Means Clustering", "Unsupervised grouping of data."],
  ["Hierarchical Clustering", "Tree-based clustering methods."],
  ["DBSCAN", "Density-based spatial clustering."],
  ["Principal Component Analysis", "Dimensionality reduction."],
  ["Cross-Validation Techniques", "K-fold, stratified, and LOO."],
  ["Hyperparameter Tuning", "Grid search, random search, Bayesian."],
  ["Model Evaluation Metrics", "Accuracy, precision, recall, F1, AUC."],
  ["Confusion Matrix Analysis", "Understanding model errors."],
  ["Bias-Variance Tradeoff", "Underfitting vs overfitting."],
  ["Regularization (L1/L2)", "Prevent overfitting with penalties."],
  ["Pipeline & Workflow Design", "Scikit-learn pipelines."],
  ["Neural Network Fundamentals", "Neurons, layers, activations."],
  ["Forward Propagation", "How data flows through a network."],
  ["Backpropagation", "How neural networks learn."],
  ["Gradient Descent Optimization", "SGD, Adam, learning rates."],
  ["Activation Functions", "ReLU, sigmoid, tanh, softmax."],
  ["Loss Functions", "MSE, cross-entropy, custom losses."],
  ["Building Neural Nets with PyTorch", "Tensors and autograd."],
  ["Building Neural Nets with TensorFlow", "Keras sequential and functional API."],
  ["Convolutional Neural Networks (CNN)", "Image feature extraction."],
  ["CNN Architecture Design", "VGG, ResNet, inception patterns."],
  ["Image Classification", "Classify images with CNNs."],
  ["Object Detection Basics", "Locate objects in images."],
  ["Image Segmentation", "Pixel-level classification."],
  ["Data Augmentation", "Expand training data artificially."],
  ["Transfer Learning", "Use pre-trained models for new tasks."],
  ["Recurrent Neural Networks (RNN)", "Sequential data processing."],
  ["LSTM Networks", "Long-term memory for sequences."],
  ["GRU Networks", "Simplified recurrent units."],
  ["Sequence-to-Sequence Models", "Input sequence to output sequence."],
  ["Attention Mechanism", "Focus on relevant parts of input."],
  ["Transformer Architecture", "Self-attention and modern NLP."],
  ["BERT & Language Models", "Pre-trained language understanding."],
  ["GPT & Text Generation", "Autoregressive language models."],
  ["Tokenization & Embeddings", "Convert text to numbers."],
  ["Sentiment Analysis", "Detect emotion in text."],
  ["Named Entity Recognition", "Extract entities from text."],
  ["Text Classification", "Categorize documents automatically."],
  ["Text Summarization", "Generate concise summaries."],
  ["Question Answering Systems", "Build QA models."],
  ["Chatbot Architecture", "Design conversational AI systems."],
  ["Speech Recognition Basics", "Convert audio to text."],
  ["Recommendation Systems", "Collaborative and content filtering."],
  ["Time Series Forecasting", "Predict future values from history."],
  ["Anomaly Detection", "Find unusual patterns in data."],
  ["Generative Adversarial Networks (GAN)", "Generate realistic data."],
  ["Variational Autoencoders (VAE)", "Learn data distributions."],
  ["Reinforcement Learning Basics", "Agents, rewards, environments."],
  ["Q-Learning", "Value-based reinforcement learning."],
  ["Policy Gradient Methods", "Direct policy optimization."],
  ["Deep Reinforcement Learning", "DQN and A3C."],
  ["Multi-Agent Systems", "Multiple AI agents interacting."],
  ["AI Ethics & Bias", "Fairness, accountability, transparency."],
  ["Explainable AI (XAI)", "Make AI decisions interpretable."],
  ["AI Safety & Alignment", "Building safe AI systems."],
  ["Model Compression", "Pruning, quantization, distillation."],
  ["Edge AI & Mobile Deployment", "Run models on devices."],
  ["MLOps Fundamentals", "CI/CD for machine learning."],
  ["Model Versioning (MLflow)", "Track experiments and models."],
  ["Data Version Control (DVC)", "Version control for datasets."],
  ["Model Serving with FastAPI", "Deploy models as APIs."],
  ["Docker for ML", "Containerize ML applications."],
  ["Kubernetes for ML", "Orchestrate ML services at scale."],
  ["Cloud ML Services (AWS/GCP)", "Use managed ML platforms."],
  ["AutoML", "Automated machine learning pipelines."],
  ["Feature Stores", "Centralized feature management."],
  ["A/B Testing for ML", "Validate model improvements."],
  ["Monitoring ML in Production", "Detect model drift and failures."],
  ["Building an AI Startup", "From idea to product."],
  ["AI Product Design", "Design AI-powered user experiences."],
  ["Computer Vision Applications", "Real-world CV use cases."],
  ["NLP Applications", "Real-world NLP use cases."],
  ["AI in Healthcare", "Medical imaging and diagnostics."],
  ["AI in Finance", "Fraud detection and trading."],
  ["AI in Gaming", "Game AI and procedural generation."],
  ["Research Paper Reading", "How to read and implement papers."],
  ["Building Your Own AI Framework", "Create a mini deep learning library."],
  ["Capstone: Build a Complete AI System", "End-to-end AI application."],
  ["AI Interview Preparation", "Common AI/ML interview questions."],
  ["AI Career Guide", "Landing your first AI job."],
];

// ==================== GAME DEV (100 lessons) ====================
const gameDevTopics: [string, string][] = [
  ["Game Loop Fundamentals", "The core loop: input, update, render."],
  ["Player Input Handling", "Keyboard, mouse, and gamepad input."],
  ["Game State Management", "Menus, playing, paused, game over."],
  ["2D Coordinate Systems", "Screen space and world coordinates."],
  ["Sprite & Animation Basics", "Display and animate characters."],
  ["Movement & Physics", "Velocity, acceleration, gravity."],
  ["Collision Detection (AABB)", "Axis-aligned bounding box collisions."],
  ["Collision Response", "Bouncing, sliding, and stopping."],
  ["Circle & Polygon Collision", "Advanced collision shapes."],
  ["Tile-Based Maps", "Build worlds with tile grids."],
  ["Camera Systems", "Follow player, scroll, and zoom."],
  ["Particle Effects", "Explosions, sparks, and trails."],
  ["Sound Effects & Music", "Audio playback and management."],
  ["Scoring Systems", "Points, combos, multipliers."],
  ["High Score & Leaderboards", "Track and display top scores."],
  ["HUD & UI Design", "Health bars, minimaps, menus."],
  ["Character Stats & Leveling", "RPG stat systems."],
  ["Inventory Systems", "Items, equipment, and crafting."],
  ["Enemy AI: Patrol", "Enemies that walk set paths."],
  ["Enemy AI: Chase & Flee", "Enemies that pursue or run."],
  ["Enemy AI: State Machines", "Complex behavior with FSMs."],
  ["Boss Fights", "Design multi-phase boss encounters."],
  ["Pathfinding (A*)", "Navigate complex environments."],
  ["Nav Meshes", "Navigation for 3D and complex 2D."],
  ["Procedural Generation Basics", "Random but structured content."],
  ["Dungeon Generation", "Generate random dungeon layouts."],
  ["Terrain Generation", "Perlin noise and height maps."],
  ["Loot Tables & Drops", "Random item generation systems."],
  ["Save & Load Systems", "Serialize and persist game state."],
  ["Checkpoint Systems", "Save progress at key points."],
  ["Platformer Mechanics", "Jump, double jump, wall slide."],
  ["Top-Down Movement", "8-directional and twin-stick."],
  ["Side-Scrolling Design", "Parallax and infinite scroll."],
  ["Fighting Game Mechanics", "Combos, hitboxes, frame data."],
  ["Racing Game Physics", "Acceleration, drift, track design."],
  ["Puzzle Game Logic", "Match-3, sliding, and logic puzzles."],
  ["Card Game Systems", "Deck building and card effects."],
  ["Turn-Based Combat", "RPG battle systems."],
  ["Real-Time Strategy (RTS)", "Unit selection and commands."],
  ["Tower Defense Mechanics", "Waves, towers, and upgrades."],
  ["Dialogue Systems", "Branching conversations."],
  ["Quest Systems", "Track objectives and rewards."],
  ["Cutscenes & Storytelling", "Narrative delivery in games."],
  ["World Building", "Lore, maps, and environments."],
  ["Character Design", "Create memorable game characters."],
  ["Level Design Principles", "Flow, pacing, and difficulty."],
  ["Difficulty Scaling", "Adaptive and progressive difficulty."],
  ["Achievements & Trophies", "Reward systems for players."],
  ["Multiplayer Basics", "Turn-based multiplayer logic."],
  ["Real-Time Multiplayer", "Sync state between players."],
  ["Networking for Games", "Client-server architecture."],
  ["Lag Compensation", "Handle network latency."],
  ["Game Economy Design", "Currency, shops, and balance."],
  ["Monetization Strategies", "Ethical game monetization."],
  ["Game Analytics", "Track player behavior."],
  ["Playtesting Methods", "Get useful feedback from players."],
  ["Game Balance", "Tune numbers for fun gameplay."],
  ["Accessibility in Games", "Make games playable by everyone."],
  ["Localization", "Translate games for global audience."],
  ["Pygame Setup & Basics", "2D game framework for Python."],
  ["Pygame Sprites & Groups", "Manage game objects efficiently."],
  ["Pygame Events & Input", "Handle user input in Pygame."],
  ["Pygame Collision & Physics", "Game physics with Pygame."],
  ["Pygame Audio", "Sound and music in Pygame."],
  ["Building a Platformer with Pygame", "Complete platformer game."],
  ["Building an RPG with Pygame", "Complete RPG game."],
  ["Building a Shooter with Pygame", "Complete shooter game."],
  ["Building a Puzzle Game", "Complete puzzle game."],
  ["Phaser.js Setup", "HTML5 game framework."],
  ["Phaser.js Sprites & Physics", "Game objects with Arcade physics."],
  ["Phaser.js Scenes & Transitions", "Multi-scene games."],
  ["Phaser.js Tilemaps", "Load and render tile maps."],
  ["Phaser.js Multiplayer", "Online Phaser games."],
  ["3D Game Concepts", "Introduction to 3D game development."],
  ["Three.js Basics", "3D rendering in the browser."],
  ["3D Models & Textures", "Load and display 3D assets."],
  ["3D Lighting & Shadows", "Illuminate 3D scenes."],
  ["3D Camera & Controls", "Navigate 3D environments."],
  ["3D Physics with Cannon.js", "Physics in 3D games."],
  ["Shader Programming Basics", "Custom visual effects."],
  ["Post-Processing Effects", "Bloom, blur, and color grading."],
  ["Game Optimization", "Performance tuning for games."],
  ["Memory Management for Games", "Efficient resource usage."],
  ["Asset Pipeline", "Manage art, audio, and data."],
  ["Game Design Documents", "Plan games before building."],
  ["Prototyping & Iteration", "Build fast, test, improve."],
  ["Game Jams", "Build a game in 48 hours."],
  ["Publishing on Itch.io", "Share games with the world."],
  ["Publishing on Steam", "Steamworks and distribution."],
  ["Mobile Game Development", "Games for phones and tablets."],
  ["Console Game Basics", "Understanding console platforms."],
  ["VR Game Development Intro", "Virtual reality fundamentals."],
  ["AR Game Development Intro", "Augmented reality games."],
  ["Game Studio Management", "Run a game dev team."],
  ["Game Marketing", "Build hype and launch well."],
  ["Community Building", "Discord, forums, social media."],
  ["Live Service Games", "Updates, seasons, and events."],
  ["Capstone: Build Your Dream Game", "Your ultimate game project."],
  ["Game Dev Portfolio", "Showcase your best work."],
  ["Game Dev Career Guide", "Landing your first game job."],
  ["Game Dev Interview Prep", "Technical and design interviews."],
];

// ==================== DATA ENGINEER (100 lessons) ====================
const dataEngTopics: [string, string][] = [
  ["What is Data Engineering?", "The role and responsibilities."],
  ["SQL Fundamentals", "SELECT, WHERE, JOIN, GROUP BY."],
  ["Advanced SQL", "Window functions, CTEs, subqueries."],
  ["SQL Performance Tuning", "Indexes, query plans, optimization."],
  ["Database Design", "Normalization, schemas, relationships."],
  ["PostgreSQL Deep Dive", "Advanced Postgres features."],
  ["MySQL & MariaDB", "MySQL-specific features and tuning."],
  ["SQLite for Prototyping", "Embedded database for development."],
  ["NoSQL: MongoDB", "Document-based database fundamentals."],
  ["NoSQL: Redis", "In-memory data store and caching."],
  ["NoSQL: DynamoDB", "AWS managed NoSQL database."],
  ["Data Modeling", "Star schema, snowflake, data vault."],
  ["ETL Fundamentals", "Extract, Transform, Load pipelines."],
  ["Python for ETL", "Build pipelines with Python."],
  ["Apache Spark Basics", "Distributed data processing."],
  ["PySpark DataFrames", "Spark with Python."],
  ["Apache Kafka Basics", "Event streaming platform."],
  ["Kafka Producers & Consumers", "Build real-time data flows."],
  ["Apache Airflow Basics", "Workflow orchestration."],
  ["Airflow DAGs & Operators", "Build complex workflows."],
  ["dbt (Data Build Tool)", "Transform data in the warehouse."],
  ["Data Quality Testing", "Validate data accuracy."],
  ["Great Expectations", "Data quality framework."],
  ["Data Catalogs", "Discover and document data."],
  ["Metadata Management", "Track data lineage and schemas."],
  ["Data Governance", "Policies, access, and compliance."],
  ["GDPR & Data Privacy", "Legal requirements for data."],
  ["Data Security", "Encryption, masking, access control."],
  ["Data Warehousing Concepts", "OLAP vs OLTP."],
  ["Snowflake Data Cloud", "Cloud data warehouse."],
  ["Google BigQuery", "Serverless analytics warehouse."],
  ["Amazon Redshift", "AWS data warehouse."],
  ["Databricks & Lakehouse", "Unified analytics platform."],
  ["Delta Lake", "ACID transactions for data lakes."],
  ["Data Lakes vs Warehouses", "When to use which."],
  ["Apache Parquet & ORC", "Columnar file formats."],
  ["Apache Avro & JSON", "Row-based serialization."],
  ["File Format Comparison", "Choose the right format."],
  ["Batch Processing Patterns", "Large-scale batch data."],
  ["Stream Processing Patterns", "Real-time data processing."],
  ["Lambda Architecture", "Batch + stream processing."],
  ["Kappa Architecture", "Stream-only processing."],
  ["Event Sourcing", "Store state as events."],
  ["Change Data Capture (CDC)", "Track database changes."],
  ["APIs & Data Collection", "REST, GraphQL, webhooks."],
  ["Web Scraping at Scale", "Collect data from websites."],
  ["Data Validation Frameworks", "Ensure data quality."],
  ["Schema Registry", "Manage evolving data schemas."],
  ["Data Contracts", "Agreements between producers/consumers."],
  ["Monitoring & Alerting", "Track pipeline health."],
  ["Logging for Pipelines", "Debug and audit data flows."],
  ["Error Handling in Pipelines", "Retry, dead letter, backfill."],
  ["Idempotent Pipelines", "Safe to re-run without duplicates."],
  ["Backfilling Data", "Reprocess historical data."],
  ["Data Partitioning", "Optimize storage and queries."],
  ["Data Compression", "Reduce storage costs."],
  ["Cloud Storage (S3/GCS/Azure)", "Object storage for data."],
  ["Infrastructure as Code", "Terraform for data infrastructure."],
  ["Docker for Data Engineering", "Containerize pipelines."],
  ["Kubernetes for Data", "Orchestrate data workloads."],
  ["CI/CD for Pipelines", "Automated testing and deployment."],
  ["Git for Data Engineering", "Version control best practices."],
  ["Python Packaging for Pipelines", "Reusable pipeline libraries."],
  ["Testing Data Pipelines", "Unit and integration tests."],
  ["Performance Optimization", "Speed up slow pipelines."],
  ["Cost Optimization", "Reduce cloud data costs."],
  ["Data Mesh Architecture", "Decentralized data ownership."],
  ["Data Fabric", "Unified data management."],
  ["Reverse ETL", "Push warehouse data to tools."],
  ["Feature Stores", "ML feature management."],
  ["Real-Time Analytics", "Live dashboards and metrics."],
  ["Business Intelligence (BI)", "Connect data to dashboards."],
  ["Tableau & Looker Basics", "BI tool fundamentals."],
  ["Data Storytelling", "Present data insights clearly."],
  ["A/B Test Data Pipelines", "Support experimentation."],
  ["Recommendation Data Pipelines", "Feed ML recommendation systems."],
  ["Search Data Pipelines", "Power search with Elasticsearch."],
  ["Geospatial Data", "Handle location-based data."],
  ["Time Series Data", "Optimize for temporal data."],
  ["Log Analytics Pipeline", "Process application logs."],
  ["Clickstream Analytics", "Track user behavior data."],
  ["IoT Data Pipelines", "Handle sensor and device data."],
  ["Healthcare Data (HIPAA)", "Compliant healthcare pipelines."],
  ["Financial Data Pipelines", "Trading and banking data."],
  ["E-commerce Data", "Product, order, and customer data."],
  ["Social Media Data", "Process social platform data."],
  ["Data Engineering on AWS", "AWS data services overview."],
  ["Data Engineering on GCP", "GCP data services overview."],
  ["Data Engineering on Azure", "Azure data services overview."],
  ["Multi-Cloud Data Strategy", "Work across cloud providers."],
  ["Open Source Data Stack", "Build with free tools."],
  ["Data Team Organization", "Roles and team structures."],
  ["Data Engineer Interview Prep", "Technical interview questions."],
  ["System Design for Data", "Design scalable data systems."],
  ["Building a Data Platform", "End-to-end platform design."],
  ["Data Engineering Portfolio", "Showcase your best projects."],
  ["Capstone: Enterprise Data Platform", "Build a complete system."],
  ["Data Engineering Trends 2026", "What's next in the field."],
  ["Contributing to Open Source Data", "Give back to the community."],
  ["Data Engineering Career Guide", "From junior to staff engineer."],
];

// ==================== MOBILE DEV (100 lessons) ====================
const mobileDevTopics: [string, string][] = [
  ["Mobile Development Overview", "Native vs cross-platform approaches."],
  ["React Native Setup", "Install and configure your environment."],
  ["React Native Core Components", "View, Text, Image, ScrollView."],
  ["Styling in React Native", "StyleSheet and flexbox layouts."],
  ["React Native Navigation", "Stack, tab, and drawer navigation."],
  ["React Native Lists", "FlatList and SectionList for data."],
  ["React Native Forms", "TextInput, Switch, Picker components."],
  ["React Native State Management", "useState and useReducer."],
  ["React Native Context API", "Global state without Redux."],
  ["React Native AsyncStorage", "Persist data locally."],
  // ... generate remaining topics
  ...Array.from({ length: 90 }, (_, i) => {
    const topics: [string, string][] = [
      ["React Native Animations", "Animated API and Reanimated."],
      ["React Native Gestures", "Pan, pinch, and tap handlers."],
      ["React Native Camera", "Access device camera."],
      ["React Native Maps", "Display maps and markers."],
      ["React Native Push Notifications", "Send and receive notifications."],
      ["React Native Networking", "Fetch API and Axios."],
      ["React Native Authentication", "Login flows and token storage."],
      ["React Native Deep Linking", "Link to specific app screens."],
      ["React Native Permissions", "Request device permissions."],
      ["React Native SQLite", "Local relational database."],
      ["React Native Firebase", "Backend as a service."],
      ["React Native Testing", "Jest and Testing Library."],
      ["React Native Performance", "Optimize rendering speed."],
      ["React Native Debugging", "Debug tools and techniques."],
      ["React Native TypeScript", "Type-safe mobile development."],
      ["React Native Custom Components", "Build reusable components."],
      ["React Native Themes", "Dark mode and theming."],
      ["React Native Internationalization", "Multi-language apps."],
      ["React Native Accessibility", "Make apps accessible."],
      ["React Native Audio & Video", "Media playback."],
      ["React Native Charts", "Data visualization in apps."],
      ["React Native Social Login", "Google, Apple, Facebook sign-in."],
      ["React Native In-App Purchases", "Monetize with purchases."],
      ["React Native Ads", "AdMob integration."],
      ["React Native Offline Mode", "Work without internet."],
      ["React Native Background Tasks", "Run tasks in background."],
      ["React Native Biometrics", "Face ID and fingerprint."],
      ["React Native Bluetooth", "Connect to BLE devices."],
      ["React Native QR Codes", "Scan and generate QR codes."],
      ["React Native File System", "Read and write files."],
      ["Expo Overview", "Simplified React Native workflow."],
      ["Expo Router", "File-based routing for mobile."],
      ["Expo Modules", "Access native features easily."],
      ["Expo EAS Build", "Cloud builds for mobile."],
      ["Expo EAS Submit", "Submit to app stores."],
      ["iOS Development Basics", "iOS-specific considerations."],
      ["Android Development Basics", "Android-specific considerations."],
      ["App Architecture (MVVM)", "Model-View-ViewModel pattern."],
      ["State Management (Redux)", "Predictable state for complex apps."],
      ["State Management (Zustand)", "Simple state for React Native."],
      ["GraphQL with Apollo Mobile", "Efficient data fetching."],
      ["REST API Best Practices", "Mobile API patterns."],
      ["Caching Strategies", "Cache data for speed."],
      ["Image Caching & Optimization", "Fast image loading."],
      ["App Security", "Secure storage and communication."],
      ["Certificate Pinning", "Prevent man-in-the-middle attacks."],
      ["Code Push (OTA Updates)", "Update without app store."],
      ["Feature Flags", "Toggle features remotely."],
      ["Analytics Integration", "Track user behavior."],
      ["Crash Reporting", "Detect and fix crashes."],
      ["A/B Testing Mobile", "Test different experiences."],
      ["App Store Optimization (ASO)", "Improve app store ranking."],
      ["App Screenshots & Preview", "Design store listing assets."],
      ["App Review Guidelines", "Pass Apple and Google review."],
      ["Beta Testing (TestFlight)", "Distribute beta builds."],
      ["Continuous Integration", "Automated mobile builds."],
      ["Continuous Deployment", "Automated store submissions."],
      ["Monorepo for Mobile", "Share code web and mobile."],
      ["Design Systems for Mobile", "Consistent mobile UI."],
      ["Micro-Frontend Mobile", "Modular mobile architecture."],
      ["Native Modules", "Bridge to native iOS/Android code."],
      ["Turbo Modules", "New architecture native modules."],
      ["Fabric Renderer", "New React Native rendering."],
      ["Hermes Engine", "Optimized JavaScript engine."],
      ["Mobile Performance Profiling", "Find and fix slow code."],
      ["Memory Leak Detection", "Fix memory issues."],
      ["Bundle Size Optimization", "Reduce app download size."],
      ["Splash Screen Design", "First impression matters."],
      ["App Icon Design", "Create recognizable icons."],
      ["Onboarding Flow Design", "Welcome new users."],
      ["Settings & Preferences", "User configuration screens."],
      ["Search Implementation", "In-app search features."],
      ["Chat UI Implementation", "Build messaging interfaces."],
      ["E-commerce Mobile App", "Shopping app patterns."],
      ["Social Media Mobile App", "Feed and profile patterns."],
      ["Fitness/Health App", "Tracking and goals."],
      ["News/Content App", "Article reading experience."],
      ["Maps & Location App", "Location-based features."],
      ["Food Delivery App UI", "Order and delivery tracking."],
      ["Banking/Finance App", "Secure financial interfaces."],
      ["Education App", "Learning on mobile."],
      ["Music/Podcast App", "Audio streaming experience."],
      ["Capstone: Build a Complete App", "Your best mobile project."],
      ["Publishing to App Store", "Submit to Apple App Store."],
      ["Publishing to Google Play", "Submit to Google Play Store."],
      ["Mobile Dev Portfolio", "Showcase your mobile work."],
      ["Mobile Dev Interview Prep", "Technical interview questions."],
      ["Mobile Dev Career Guide", "Landing your first mobile job."],
      ["Mobile Dev Trends 2026", "What's next in mobile."],
    ];
    return topics[i % topics.length];
  }),
];

// Build all paths
export const SPECIALIZATION_PATHS: SpecializationPath[] = [
  {
    id: "web-designer", name: "Web Designer", icon: "🎨", color: "pink",
    language: "javascript", description: "Design and build beautiful, responsive websites from scratch. From HTML/CSS to React and deployment.",
    lessons: generateLessons("webdesign", webDesignTopics, "javascript"),
    capstoneTitle: "Build a Professional Portfolio Website",
    capstoneDescription: "Design and build a stunning portfolio website with responsive layout, animations, dark mode, and multiple pages.",
    capstoneRequirements: ["Responsive design (mobile + desktop)", "At least 5 pages with navigation", "CSS animations and transitions", "Contact form with validation", "Project gallery with filters", "Dark/light mode toggle", "SEO optimized", "Deployed to production"],
    certificateName: "Certified Web Designer",
  },
  {
    id: "ai-ml", name: "AI & Machine Learning", icon: "🤖", color: "purple",
    language: "python", description: "Build intelligent systems that learn from data. From linear regression to deep learning and deployment.",
    lessons: generateLessons("ai", aiTopics, "python"),
    capstoneTitle: "Build Your Own AI System",
    capstoneDescription: "Create a complete AI application: collect data, train a model, serve predictions via API, and deploy.",
    capstoneRequirements: ["Data collection and preprocessing pipeline", "At least 2 different model types compared", "Model evaluation with metrics", "REST API for predictions", "Model versioning and logging", "Deployed and serving requests", "Documentation and README"],
    certificateName: "Certified AI Developer",
  },
  {
    id: "game-dev", name: "Game Developer", icon: "🎮", color: "green",
    language: "python", description: "Create games from simple to complex. Physics, AI, multiplayer, 3D, and publishing.",
    lessons: generateLessons("gamedev", gameDevTopics, "python"),
    capstoneTitle: "Build Your Dream Game",
    capstoneDescription: "Create a complete, polished game with multiple levels, enemies, progression, and publishing.",
    capstoneRequirements: ["Complete game loop with menus", "At least 5 levels or stages", "Enemy AI with multiple behaviors", "Scoring, lives, and progression", "Save/load game state", "Sound effects and music", "Published on itch.io or similar", "README with screenshots"],
    certificateName: "Certified Game Developer",
  },
  {
    id: "data-engineer", name: "Data Engineer", icon: "📊", color: "blue",
    language: "python", description: "Build data pipelines, warehouses, and analytics platforms at scale.",
    lessons: generateLessons("dataeng", dataEngTopics, "python"),
    capstoneTitle: "Build an Enterprise Data Platform",
    capstoneDescription: "Create a complete data platform with multiple pipelines, a warehouse, scheduling, monitoring, and dashboards.",
    capstoneRequirements: ["ETL pipeline with 5+ data sources", "Data warehouse with star schema", "Automated scheduling with Airflow", "Data quality validation", "Monitoring and alerting", "BI dashboard with key metrics", "Documentation and data catalog", "Deployed on cloud infrastructure"],
    certificateName: "Certified Data Engineer",
  },
  {
    id: "mobile-dev", name: "Mobile App Developer", icon: "📱", color: "cyan",
    language: "javascript", description: "Build cross-platform mobile apps with React Native. From basics to publishing on app stores.",
    lessons: generateLessons("mobile", mobileDevTopics, "javascript"),
    capstoneTitle: "Build and Publish a Mobile App",
    capstoneDescription: "Create a complete mobile application and publish it to the App Store and Google Play.",
    capstoneRequirements: ["Multiple screens with navigation", "State management and data persistence", "API integration with error handling", "Push notifications", "Authentication flow", "App icon and splash screen", "Published on at least one store", "5-star worthy UX"],
    certificateName: "Certified Mobile Developer",
  },
];

// ==================== ADVANCED LESSONS ====================
const advancedPythonTitles = [
  "Metaclasses Deep Dive", "Descriptors & Protocols", "Async Generators & Streams",
  "C Extensions with ctypes", "Memory Profiling & Optimization", "Custom Decorators Framework",
  "Building a Web Framework", "Compiler Design Basics", "Distributed Systems with Python",
  "Kubernetes & Docker for Python", "GraphQL Server Implementation", "Real-Time WebSockets",
  "Security & Cryptography", "Building a Package Manager", "Contributing to Open Source",
  "System Design Patterns", "High-Performance Computing", "Building a Database Engine",
  "ML Model Deployment (MLOps)", "Staff Engineer Best Practices",
];

const advancedJsTitles = [
  "V8 Engine Internals", "WebAssembly Integration", "Custom Bundler Design",
  "Micro-Frontend Architecture", "Real-Time Collaboration (CRDT)", "Browser Extension Development",
  "WebGL & 3D Graphics", "Service Worker Advanced Patterns", "Custom React Renderer",
  "Compiler/Transpiler Design", "GraphQL Subscriptions", "Edge Computing with Workers",
  "Security Hardening", "Monorepo Architecture", "Contributing to Open Source",
  "System Design for Frontend", "Performance Engineering", "Building a JS Runtime",
  "Full-Stack TypeScript Patterns", "Principal Engineer Best Practices",
];

export const ADVANCED_PYTHON = advancedPythonTitles.map((title, i) => ({
  id: `adv-python-${i + 1}`, title, description: `Advanced Python: ${title}.`,
}));

export const ADVANCED_JS = advancedJsTitles.map((title, i) => ({
  id: `adv-js-${i + 1}`, title, description: `Advanced JavaScript: ${title}.`,
}));

export function getPathById(id: string): SpecializationPath | undefined {
  return SPECIALIZATION_PATHS.find((p) => p.id === id);
}
