export interface PathLesson {
  id: string;
  title: string;
  description: string;
  content: string;
  codeExample: string;
  order: number;
}

export interface SpecializationPath {
  id: string;
  name: string;
  icon: string;
  color: string;
  language: "python" | "javascript";
  description: string;
  prerequisite: string; // "python-100" or "js-100"
  lessons: PathLesson[];
  capstoneTitle: string;
  capstoneDescription: string;
  capstoneRequirements: string[];
  certificateName: string;
}

// ==================== JAVASCRIPT PATHS ====================

const webDesignerLessons: PathLesson[] = [
  { id: "webdesign-1", order: 1, title: "HTML Foundations", description: "Structure web pages with semantic HTML.", content: "HTML is the skeleton of every website. Learn semantic elements like <header>, <nav>, <main>, <article>, <section>, and <footer> to create well-structured pages.\n\n**Key concepts:**\n- Document structure\n- Semantic elements\n- Accessibility basics\n- Forms and inputs", codeExample: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>My Website</title>\n</head>\n<body>\n    <header>\n        <nav>\n            <a href=\"/\">Home</a>\n            <a href=\"/about\">About</a>\n        </nav>\n    </header>\n    <main>\n        <h1>Welcome</h1>\n        <p>My first web page!</p>\n    </main>\n    <footer>&copy; 2026</footer>\n</body>\n</html>" },
  { id: "webdesign-2", order: 2, title: "CSS Styling Basics", description: "Make things look beautiful with CSS.", content: "CSS controls how your HTML looks. Learn selectors, properties, colors, fonts, spacing, and the box model.\n\n**Key concepts:**\n- Selectors and specificity\n- Colors, fonts, spacing\n- Box model (margin, padding, border)\n- Display and positioning", codeExample: "/* Base styles */\nbody {\n    font-family: 'Inter', sans-serif;\n    margin: 0;\n    background: #0f172a;\n    color: #e2e8f0;\n}\n\n.container {\n    max-width: 1200px;\n    margin: 0 auto;\n    padding: 0 20px;\n}\n\n.hero {\n    text-align: center;\n    padding: 80px 0;\n}\n\n.hero h1 {\n    font-size: 3rem;\n    background: linear-gradient(to right, #6366f1, #a855f7);\n    -webkit-background-clip: text;\n    -webkit-text-fill-color: transparent;\n}" },
  { id: "webdesign-3", order: 3, title: "Flexbox Layout", description: "Master flexible box layouts for responsive design.", content: "Flexbox is the modern way to create layouts. It handles alignment, distribution, and ordering of elements in one dimension.\n\n**Key concepts:**\n- display: flex\n- justify-content and align-items\n- flex-direction and flex-wrap\n- gap, flex-grow, flex-shrink", codeExample: "/* Navigation with flexbox */\n.nav {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n    padding: 16px 24px;\n}\n\n.nav-links {\n    display: flex;\n    gap: 24px;\n}\n\n/* Card grid with flexbox */\n.cards {\n    display: flex;\n    flex-wrap: wrap;\n    gap: 20px;\n}\n\n.card {\n    flex: 1 1 300px;\n    padding: 24px;\n    border-radius: 12px;\n    background: #1e293b;\n}" },
  { id: "webdesign-4", order: 4, title: "CSS Grid", description: "Build complex two-dimensional layouts.", content: "CSS Grid handles two-dimensional layouts — rows AND columns. Perfect for page layouts, galleries, and dashboards.\n\n**Key concepts:**\n- display: grid\n- grid-template-columns/rows\n- grid-gap\n- grid-area and named areas", codeExample: ".dashboard {\n    display: grid;\n    grid-template-columns: 250px 1fr;\n    grid-template-rows: 60px 1fr;\n    grid-template-areas:\n        \"sidebar header\"\n        \"sidebar main\";\n    height: 100vh;\n}\n\n.header { grid-area: header; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }\n\n/* Responsive gallery */\n.gallery {\n    display: grid;\n    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\n    gap: 16px;\n}" },
  { id: "webdesign-5", order: 5, title: "Responsive Design", description: "Make websites work on any screen size.", content: "Responsive design ensures your website looks great on phones, tablets, and desktops. Use media queries, relative units, and mobile-first approach.\n\n**Key concepts:**\n- Media queries\n- Mobile-first design\n- Relative units (rem, em, %)\n- Responsive images", codeExample: "/* Mobile first */\n.container {\n    padding: 16px;\n}\n\n.grid {\n    display: grid;\n    grid-template-columns: 1fr;\n    gap: 16px;\n}\n\n/* Tablet */\n@media (min-width: 768px) {\n    .grid {\n        grid-template-columns: repeat(2, 1fr);\n    }\n}\n\n/* Desktop */\n@media (min-width: 1024px) {\n    .container {\n        max-width: 1200px;\n        margin: 0 auto;\n    }\n    .grid {\n        grid-template-columns: repeat(3, 1fr);\n    }\n}" },
  { id: "webdesign-6", order: 6, title: "CSS Animations & Transitions", description: "Add motion and interactivity to your designs.", content: "Animations bring websites to life. Learn transitions for hover effects and keyframe animations for complex motion.\n\n**Key concepts:**\n- transition property\n- @keyframes animations\n- transform (scale, rotate, translate)\n- animation timing functions", codeExample: "/* Hover transition */\n.button {\n    padding: 12px 24px;\n    background: #6366f1;\n    border-radius: 8px;\n    transition: all 0.3s ease;\n}\n.button:hover {\n    transform: translateY(-2px);\n    box-shadow: 0 10px 25px rgba(99, 102, 241, 0.3);\n}\n\n/* Keyframe animation */\n@keyframes fadeInUp {\n    from {\n        opacity: 0;\n        transform: translateY(20px);\n    }\n    to {\n        opacity: 1;\n        transform: translateY(0);\n    }\n}\n.animate {\n    animation: fadeInUp 0.6s ease forwards;\n}" },
  { id: "webdesign-7", order: 7, title: "Tailwind CSS", description: "Build designs rapidly with utility-first CSS.", content: "Tailwind CSS lets you style elements using utility classes directly in HTML. No writing CSS files — just add classes.\n\n**Key concepts:**\n- Utility classes\n- Responsive prefixes (sm:, md:, lg:)\n- Hover/focus states\n- Custom configuration", codeExample: "<!-- Hero section with Tailwind -->\n<section class=\"min-h-screen bg-gradient-to-br from-indigo-600 to-purple-700 flex items-center justify-center px-4\">\n    <div class=\"text-center max-w-3xl\">\n        <h1 class=\"text-5xl md:text-7xl font-extrabold text-white mb-6\">\n            Build Beautiful Websites\n        </h1>\n        <p class=\"text-xl text-indigo-200 mb-8\">\n            Design and develop stunning websites with modern tools.\n        </p>\n        <div class=\"flex gap-4 justify-center\">\n            <button class=\"px-8 py-3 bg-white text-indigo-600 rounded-xl font-bold hover:bg-indigo-50 transition\">\n                Get Started\n            </button>\n        </div>\n    </div>\n</section>" },
  { id: "webdesign-8", order: 8, title: "React Components for UI", description: "Build reusable UI components with React.", content: "React lets you build UIs from reusable components. Each component manages its own state and renders HTML.\n\n**Key concepts:**\n- Component architecture\n- Props and children\n- useState for interactivity\n- Component composition", codeExample: "function Card({ title, description, image, link }) {\n    return (\n        <div className=\"bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition\">\n            <img src={image} alt={title} className=\"w-full h-48 object-cover\" />\n            <div className=\"p-6\">\n                <h3 className=\"text-xl font-bold mb-2\">{title}</h3>\n                <p className=\"text-gray-600 mb-4\">{description}</p>\n                <a href={link} className=\"text-indigo-600 font-medium hover:underline\">\n                    Learn more →\n                </a>\n            </div>\n        </div>\n    );\n}\n\nfunction Portfolio() {\n    const projects = [\n        { title: 'E-commerce', description: 'Online store', image: '/shop.jpg', link: '#' },\n        { title: 'Blog', description: 'Personal blog', image: '/blog.jpg', link: '#' },\n    ];\n    return (\n        <div className=\"grid md:grid-cols-2 gap-6\">\n            {projects.map(p => <Card key={p.title} {...p} />)}\n        </div>\n    );\n}" },
  { id: "webdesign-9", order: 9, title: "Design Systems & Color Theory", description: "Create consistent, professional designs.", content: "A design system ensures your website looks cohesive. Learn about color palettes, typography scales, spacing systems, and component libraries.\n\n**Key concepts:**\n- Color theory and palettes\n- Typography scale\n- Spacing system (4px/8px grid)\n- Component tokens", codeExample: "/* Design system tokens */\n:root {\n    /* Colors */\n    --primary: #6366f1;\n    --primary-hover: #818cf8;\n    --bg: #0f172a;\n    --card: #1e293b;\n    --text: #e2e8f0;\n    --muted: #94a3b8;\n\n    /* Typography */\n    --font-sans: 'Inter', system-ui, sans-serif;\n    --text-xs: 0.75rem;\n    --text-sm: 0.875rem;\n    --text-base: 1rem;\n    --text-lg: 1.125rem;\n    --text-xl: 1.25rem;\n    --text-2xl: 1.5rem;\n    --text-4xl: 2.25rem;\n\n    /* Spacing */\n    --space-1: 4px;\n    --space-2: 8px;\n    --space-3: 12px;\n    --space-4: 16px;\n    --space-6: 24px;\n    --space-8: 32px;\n\n    /* Radius */\n    --radius-sm: 6px;\n    --radius-md: 8px;\n    --radius-lg: 12px;\n    --radius-xl: 16px;\n}" },
  { id: "webdesign-10", order: 10, title: "Performance & Deployment", description: "Optimize and launch your website.", content: "Learn to optimize images, lazy load content, minimize CSS/JS, and deploy to Vercel or Netlify.\n\n**Key concepts:**\n- Image optimization\n- Lazy loading\n- Lighthouse audits\n- Deployment with Vercel", codeExample: "// Next.js optimized image\nimport Image from 'next/image';\n\nexport default function Hero() {\n    return (\n        <section>\n            <Image\n                src=\"/hero.jpg\"\n                alt=\"Hero\"\n                width={1200}\n                height={600}\n                priority\n                placeholder=\"blur\"\n            />\n        </section>\n    );\n}\n\n// Lazy load components\nimport dynamic from 'next/dynamic';\nconst HeavyChart = dynamic(() => import('./Chart'), {\n    loading: () => <p>Loading...</p>,\n    ssr: false,\n});" },
];

const aiPathLessons: PathLesson[] = [
  { id: "ai-1", order: 1, title: "What is AI & Machine Learning?", description: "Understand AI, ML, and deep learning fundamentals.", content: "Artificial Intelligence is about making machines that can think and learn. Machine Learning is a subset where computers learn from data instead of explicit rules.\n\n**Key concepts:**\n- AI vs ML vs Deep Learning\n- Supervised vs Unsupervised learning\n- Training data and models\n- Real-world applications", codeExample: "# Your first ML concept: a simple prediction\n# Given data about house sizes and prices,\n# predict the price of a new house\n\nsizes = [800, 1200, 1600, 2000, 2400]\nprices = [150000, 225000, 300000, 375000, 450000]\n\n# Simple linear relationship: price = size * 187.5\ndef predict_price(size):\n    # Linear regression by hand\n    avg_price_per_sqft = sum(p/s for s, p in zip(sizes, prices)) / len(sizes)\n    return size * avg_price_per_sqft\n\nprint(f\"Predicted price for 1800 sqft: ${predict_price(1800):,.0f}\")" },
  { id: "ai-2", order: 2, title: "Python for Data Science", description: "NumPy, Pandas, and data manipulation.", content: "Data science requires tools for handling large datasets. NumPy provides fast arrays, Pandas provides DataFrames for structured data.\n\n**Key concepts:**\n- NumPy arrays and operations\n- Pandas DataFrames\n- Data cleaning and filtering\n- Statistical analysis", codeExample: "import numpy as np\n\n# NumPy arrays\ndata = np.array([14, 23, 35, 42, 51, 67, 73, 88, 95])\nprint(f\"Mean: {data.mean():.1f}\")\nprint(f\"Std Dev: {data.std():.1f}\")\nprint(f\"Max: {data.max()}\")\n\n# Simulate Pandas-like operations\nstudents = [\n    {\"name\": \"Alice\", \"math\": 92, \"science\": 88},\n    {\"name\": \"Bob\", \"math\": 78, \"science\": 95},\n    {\"name\": \"Charlie\", \"math\": 85, \"science\": 82},\n]\n\navg_math = sum(s[\"math\"] for s in students) / len(students)\nprint(f\"\\nAverage math score: {avg_math:.1f}\")" },
  { id: "ai-3", order: 3, title: "Data Visualization", description: "Create charts and visual insights.", content: "Visualization turns data into understanding. Learn to create plots, charts, and interactive visualizations.\n\n**Key concepts:**\n- Line, bar, scatter plots\n- Histograms and distributions\n- Heatmaps and correlations\n- Interactive dashboards", codeExample: "# Data visualization concepts (text-based)\ndef bar_chart(data, title):\n    print(f\"\\n{title}\")\n    print(\"=\" * 40)\n    max_val = max(data.values())\n    for label, value in data.items():\n        bar_len = int(value / max_val * 30)\n        bar = \"█\" * bar_len\n        print(f\"{label:>10} | {bar} {value}\")\n\nsales = {\n    \"Jan\": 45,\n    \"Feb\": 52,\n    \"Mar\": 61,\n    \"Apr\": 73,\n    \"May\": 58,\n    \"Jun\": 89,\n}\n\nbar_chart(sales, \"Monthly Sales 2026\")" },
  { id: "ai-4", order: 4, title: "Linear Regression", description: "Build your first prediction model.", content: "Linear regression finds the best straight line through data points. It's the foundation of machine learning.\n\n**Key concepts:**\n- Slope and intercept\n- Cost function (MSE)\n- Gradient descent\n- Training and prediction", codeExample: "# Linear Regression from scratch\nclass LinearRegression:\n    def __init__(self):\n        self.slope = 0\n        self.intercept = 0\n\n    def fit(self, X, y):\n        n = len(X)\n        x_mean = sum(X) / n\n        y_mean = sum(y) / n\n        \n        numerator = sum((X[i] - x_mean) * (y[i] - y_mean) for i in range(n))\n        denominator = sum((X[i] - x_mean) ** 2 for i in range(n))\n        \n        self.slope = numerator / denominator\n        self.intercept = y_mean - self.slope * x_mean\n\n    def predict(self, x):\n        return self.slope * x + self.intercept\n\n# Train\nX = [1, 2, 3, 4, 5]\ny = [2, 4, 5, 4, 5]\nmodel = LinearRegression()\nmodel.fit(X, y)\nprint(f\"Prediction for x=6: {model.predict(6):.2f}\")" },
  { id: "ai-5", order: 5, title: "Classification & Decision Trees", description: "Categorize data with decision trees.", content: "Classification assigns labels to data. Decision trees make decisions by asking yes/no questions about features.\n\n**Key concepts:**\n- Classification vs regression\n- Decision tree logic\n- Feature importance\n- Overfitting and pruning", codeExample: "# Simple decision tree classifier\nclass DecisionNode:\n    def __init__(self, feature, threshold, left, right):\n        self.feature = feature\n        self.threshold = threshold\n        self.left = left\n        self.right = right\n\n    def predict(self, sample):\n        if sample[self.feature] <= self.threshold:\n            if isinstance(self.left, str): return self.left\n            return self.left.predict(sample)\n        else:\n            if isinstance(self.right, str): return self.right\n            return self.right.predict(sample)\n\n# Will someone play tennis?\n# Features: [temperature, humidity]\ntree = DecisionNode(\n    feature=1, threshold=75,\n    left=\"Play\",\n    right=DecisionNode(feature=0, threshold=80, left=\"Play\", right=\"Don't Play\")\n)\n\nprint(tree.predict([72, 60]))  # Play\nprint(tree.predict([85, 90]))  # Don't Play" },
  { id: "ai-6", order: 6, title: "Neural Networks Basics", description: "Understand how neural networks learn.", content: "Neural networks are inspired by the brain. They learn by adjusting weights through layers of connected neurons.\n\n**Key concepts:**\n- Neurons and activation functions\n- Forward propagation\n- Backpropagation\n- Loss functions", codeExample: "import math\n\ndef sigmoid(x):\n    return 1 / (1 + math.exp(-x))\n\nclass Neuron:\n    def __init__(self, weights, bias):\n        self.weights = weights\n        self.bias = bias\n\n    def forward(self, inputs):\n        total = sum(w * x for w, x in zip(self.weights, inputs)) + self.bias\n        return sigmoid(total)\n\n# AND gate neural network\nneuron = Neuron(weights=[10, 10], bias=-15)\n\nprint(f\"0 AND 0 = {neuron.forward([0, 0]):.3f}\")\nprint(f\"0 AND 1 = {neuron.forward([0, 1]):.3f}\")\nprint(f\"1 AND 0 = {neuron.forward([1, 0]):.3f}\")\nprint(f\"1 AND 1 = {neuron.forward([1, 1]):.3f}\")" },
  { id: "ai-7", order: 7, title: "Natural Language Processing", description: "Teach computers to understand text.", content: "NLP lets computers process human language. Learn tokenization, sentiment analysis, and text classification.\n\n**Key concepts:**\n- Tokenization\n- Bag of words\n- Sentiment analysis\n- Text preprocessing", codeExample: "# Simple sentiment analyzer\npositive_words = {\"good\", \"great\", \"amazing\", \"love\", \"excellent\", \"wonderful\", \"best\", \"happy\", \"fantastic\"}\nnegative_words = {\"bad\", \"terrible\", \"awful\", \"hate\", \"worst\", \"horrible\", \"poor\", \"sad\", \"angry\"}\n\ndef analyze_sentiment(text):\n    words = text.lower().split()\n    pos = sum(1 for w in words if w in positive_words)\n    neg = sum(1 for w in words if w in negative_words)\n    if pos > neg: return f\"Positive (score: +{pos - neg})\"\n    if neg > pos: return f\"Negative (score: -{neg - pos})\"\n    return \"Neutral\"\n\nreviews = [\n    \"This product is amazing and wonderful!\",\n    \"Terrible experience, the worst ever.\",\n    \"It was okay, nothing special.\",\n]\n\nfor review in reviews:\n    print(f\"{review}\")\n    print(f\"  → {analyze_sentiment(review)}\\n\")" },
  { id: "ai-8", order: 8, title: "Building a Chatbot", description: "Create an intelligent chatbot from scratch.", content: "Chatbots combine NLP with pattern matching and response generation. Build one that can hold conversations.\n\n**Key concepts:**\n- Intent recognition\n- Pattern matching\n- Context management\n- Response generation", codeExample: "import random\n\nclass ChatBot:\n    def __init__(self, name):\n        self.name = name\n        self.patterns = {\n            \"greeting\": ([\"hi\", \"hello\", \"hey\"], [\"Hello!\", \"Hi there!\", \"Hey! How can I help?\"]),\n            \"farewell\": ([\"bye\", \"goodbye\"], [\"Goodbye!\", \"See you later!\"]),\n            \"name\": ([\"your name\", \"who are you\"], [f\"I'm {name}!\", f\"My name is {name}.\"]),\n            \"help\": ([\"help\", \"assist\"], [\"I can chat, answer questions, and tell jokes!\"]),\n            \"joke\": ([\"joke\", \"funny\"], [\"Why do programmers prefer dark mode? Because light attracts bugs!\"]),\n        }\n\n    def respond(self, message):\n        msg = message.lower()\n        for intent, (triggers, responses) in self.patterns.items():\n            if any(t in msg for t in triggers):\n                return random.choice(responses)\n        return \"Interesting! Tell me more.\"\n\nbot = ChatBot(\"Atlas\")\nfor msg in [\"Hello!\", \"What's your name?\", \"Tell me a joke\", \"Bye\"]:\n    print(f\"You: {msg}\")\n    print(f\"Bot: {bot.respond(msg)}\\n\")" },
  { id: "ai-9", order: 9, title: "Image Recognition Concepts", description: "How computers see and understand images.", content: "Computer vision lets machines understand images. Learn about pixels, filters, convolutions, and how CNNs detect objects.\n\n**Key concepts:**\n- Pixels and image representation\n- Convolution filters\n- Feature detection\n- Classification from features", codeExample: "# Image processing concepts\n# Representing a 5x5 image as a grid\nimage = [\n    [0, 0, 1, 0, 0],\n    [0, 1, 1, 1, 0],\n    [1, 1, 1, 1, 1],\n    [0, 1, 1, 1, 0],\n    [0, 0, 1, 0, 0],\n]\n\ndef display(img, title):\n    print(f\"\\n{title}:\")\n    for row in img:\n        print(\" \".join(\"█\" if p else \"·\" for p in row))\n\n# Edge detection filter\ndef apply_filter(img, kernel):\n    h, w = len(img), len(img[0])\n    result = [[0]*(w-2) for _ in range(h-2)]\n    for i in range(1, h-1):\n        for j in range(1, w-1):\n            val = sum(img[i+di][j+dj] * kernel[di+1][dj+1]\n                      for di in [-1,0,1] for dj in [-1,0,1])\n            result[i-1][j-1] = 1 if val > 2 else 0\n    return result\n\nedge_kernel = [[-1,-1,-1],[-1,8,-1],[-1,-1,-1]]\n\ndisplay(image, \"Original\")\ndisplay(apply_filter(image, edge_kernel), \"Edges\")" },
  { id: "ai-10", order: 10, title: "Building Your Own AI", description: "Combine everything into a complete AI system.", content: "In this final lesson, you'll learn the architecture of a complete AI application — from data collection to model training to deployment.\n\n**Key concepts:**\n- Data pipeline design\n- Model training workflow\n- Evaluation metrics\n- Deploying AI as an API", codeExample: "# Complete mini AI system: Spam Classifier\nclass SpamClassifier:\n    def __init__(self):\n        self.spam_words = {}\n        self.ham_words = {}\n        self.spam_count = 0\n        self.ham_count = 0\n\n    def train(self, messages):\n        for text, label in messages:\n            words = text.lower().split()\n            if label == \"spam\":\n                self.spam_count += 1\n                for w in words:\n                    self.spam_words[w] = self.spam_words.get(w, 0) + 1\n            else:\n                self.ham_count += 1\n                for w in words:\n                    self.ham_words[w] = self.ham_words.get(w, 0) + 1\n\n    def predict(self, text):\n        words = text.lower().split()\n        spam_score = sum(self.spam_words.get(w, 0) for w in words)\n        ham_score = sum(self.ham_words.get(w, 0) for w in words)\n        return \"spam\" if spam_score > ham_score else \"not spam\"\n\n# Train\ndata = [\n    (\"Buy cheap pills now\", \"spam\"),\n    (\"Free money click here\", \"spam\"),\n    (\"Meeting tomorrow at 3pm\", \"ham\"),\n    (\"Hey want to grab lunch\", \"ham\"),\n    (\"Win a free iPhone now\", \"spam\"),\n    (\"Project deadline is Friday\", \"ham\"),\n]\n\nai = SpamClassifier()\nai.train(data)\n\n# Test\ntests = [\"Free pills buy now\", \"See you at the meeting\", \"Click to win money\"]\nfor t in tests:\n    print(f\"{t} → {ai.predict(t)}\")" },
];

const gameDevLessons: PathLesson[] = [
  { id: "gamedev-1", order: 1, title: "Game Loop Basics", description: "Understand the core of every game.", content: "Every game runs on a loop: get input, update state, render. Learn this fundamental pattern.", codeExample: "# Simple game loop concept\nimport time\n\nclass Game:\n    def __init__(self):\n        self.running = True\n        self.score = 0\n        self.round = 0\n\n    def update(self):\n        self.round += 1\n        self.score += 10\n\n    def render(self):\n        print(f\"Round {self.round} | Score: {self.score}\")\n\n    def run(self):\n        while self.running and self.round < 5:\n            self.update()\n            self.render()\n            self.running = self.round < 5\n\ngame = Game()\ngame.run()\nprint(f\"Game Over! Final Score: {game.score}\")" },
  { id: "gamedev-2", order: 2, title: "Player Input & Movement", description: "Handle keyboard input and player movement.", content: "Games need to respond to player actions. Learn to process input and update game state accordingly.", codeExample: "class Player:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n        self.health = 100\n\n    def move(self, direction):\n        moves = {'up': (0,-1), 'down': (0,1), 'left': (-1,0), 'right': (1,0)}\n        if direction in moves:\n            dx, dy = moves[direction]\n            self.x += dx\n            self.y += dy\n            return True\n        return False\n\n    def __str__(self):\n        return f\"Player at ({self.x},{self.y}) HP:{self.health}\"\n\np = Player(5, 5)\nfor cmd in ['up', 'up', 'right', 'right', 'down']:\n    p.move(cmd)\n    print(p)" },
  { id: "gamedev-3", order: 3, title: "Collision Detection", description: "Detect when objects touch or overlap.", content: "Collision detection is essential for games — bullets hitting enemies, players collecting items, walls blocking movement.", codeExample: "class Rect:\n    def __init__(self, x, y, w, h):\n        self.x, self.y, self.w, self.h = x, y, w, h\n\n    def collides(self, other):\n        return (self.x < other.x + other.w and\n                self.x + self.w > other.x and\n                self.y < other.y + other.h and\n                self.y + self.h > other.y)\n\nplayer = Rect(10, 10, 32, 32)\ncoin = Rect(15, 15, 16, 16)\nwall = Rect(100, 100, 50, 50)\n\nprint(f\"Player hits coin: {player.collides(coin)}\")\nprint(f\"Player hits wall: {player.collides(wall)}\")" },
  { id: "gamedev-4", order: 4, title: "Game State Management", description: "Manage menus, levels, and game over screens.", content: "Games have multiple states: menu, playing, paused, game over. Learn the state machine pattern.", codeExample: "class GameState:\n    MENU = 'menu'\n    PLAYING = 'playing'\n    PAUSED = 'paused'\n    GAME_OVER = 'game_over'\n\nclass Game:\n    def __init__(self):\n        self.state = GameState.MENU\n        self.score = 0\n        self.level = 1\n\n    def handle(self, action):\n        if self.state == GameState.MENU:\n            if action == 'start': self.state = GameState.PLAYING\n        elif self.state == GameState.PLAYING:\n            if action == 'pause': self.state = GameState.PAUSED\n            elif action == 'die': self.state = GameState.GAME_OVER\n            elif action == 'score': self.score += 100\n        elif self.state == GameState.PAUSED:\n            if action == 'resume': self.state = GameState.PLAYING\n        elif self.state == GameState.GAME_OVER:\n            if action == 'restart':\n                self.state = GameState.PLAYING\n                self.score = 0\n        print(f\"[{self.state}] Score: {self.score}\")\n\ng = Game()\nfor a in ['start','score','score','pause','resume','score','die','restart']:\n    g.handle(a)" },
  { id: "gamedev-5", order: 5, title: "Scoring & Leaderboards", description: "Track scores and rank players.", content: "Every game needs scoring. Learn to track points, combos, high scores, and persistent leaderboards.", codeExample: "class Leaderboard:\n    def __init__(self):\n        self.scores = []\n\n    def add(self, name, score):\n        self.scores.append({'name': name, 'score': score})\n        self.scores.sort(key=lambda x: x['score'], reverse=True)\n        self.scores = self.scores[:10]  # Top 10\n\n    def display(self):\n        print('\\n🏆 LEADERBOARD')\n        print('=' * 30)\n        for i, entry in enumerate(self.scores, 1):\n            medal = ['🥇','🥈','🥉'][i-1] if i <= 3 else '  '\n            print(f'{medal} #{i} {entry[\"name\"]:>10} {entry[\"score\"]:>6}')\n\nlb = Leaderboard()\nlb.add('Alice', 15000)\nlb.add('Bob', 12500)\nlb.add('Charlie', 18000)\nlb.add('Diana', 9500)\nlb.add('Eve', 21000)\nlb.display()" },
  { id: "gamedev-6", order: 6, title: "Inventory & Items", description: "Build item systems for RPGs.", content: "RPGs need inventory systems. Learn to create items, manage inventories, and handle equipment.", codeExample: "class Item:\n    def __init__(self, name, item_type, power=0):\n        self.name = name\n        self.type = item_type\n        self.power = power\n    def __str__(self):\n        return f\"{self.name} ({self.type}, +{self.power})\"\n\nclass Inventory:\n    def __init__(self, max_size=10):\n        self.items = []\n        self.max_size = max_size\n    def add(self, item):\n        if len(self.items) >= self.max_size:\n            return False\n        self.items.append(item)\n        return True\n    def show(self):\n        print(f\"Inventory ({len(self.items)}/{self.max_size}):\")\n        for i, item in enumerate(self.items, 1):\n            print(f\"  {i}. {item}\")\n\ninv = Inventory(5)\ninv.add(Item(\"Iron Sword\", \"weapon\", 15))\ninv.add(Item(\"Health Potion\", \"consumable\", 50))\ninv.add(Item(\"Shield\", \"armor\", 10))\ninv.show()" },
  { id: "gamedev-7", order: 7, title: "Enemy AI", description: "Make enemies that think and react.", content: "Game enemies need artificial intelligence. Learn patrol patterns, chasing, and difficulty scaling.", codeExample: "import random\n\nclass Enemy:\n    def __init__(self, name, x, y):\n        self.name = name\n        self.x, self.y = x, y\n        self.state = 'patrol'\n\n    def update(self, player_x, player_y):\n        dist = abs(self.x - player_x) + abs(self.y - player_y)\n        if dist < 3:\n            self.state = 'chase'\n            dx = 1 if player_x > self.x else -1 if player_x < self.x else 0\n            dy = 1 if player_y > self.y else -1 if player_y < self.y else 0\n            self.x += dx\n            self.y += dy\n        else:\n            self.state = 'patrol'\n            self.x += random.choice([-1, 0, 1])\n            self.y += random.choice([-1, 0, 1])\n\n    def __str__(self):\n        return f\"{self.name} at ({self.x},{self.y}) [{self.state}]\"\n\nenemy = Enemy(\"Goblin\", 10, 10)\nfor turn in range(6):\n    enemy.update(8, 8)\n    print(f\"Turn {turn+1}: {enemy}\")" },
  { id: "gamedev-8", order: 8, title: "Levels & World Building", description: "Create game worlds with tile maps.", content: "Game worlds are built from tiles — a grid where each cell represents terrain, walls, or objects.", codeExample: "class Level:\n    TILES = {0: '·', 1: '█', 2: '🚪', 3: '💎', 4: '👤'}\n\n    def __init__(self, grid):\n        self.grid = [row[:] for row in grid]\n\n    def display(self):\n        for row in self.grid:\n            print(' '.join(self.TILES.get(cell, '?') for cell in row))\n\nlevel1 = Level([\n    [1,1,1,1,1,1,1,1],\n    [1,4,0,0,0,0,3,1],\n    [1,0,1,1,0,1,0,1],\n    [1,0,0,0,0,1,0,1],\n    [1,1,0,1,0,0,0,1],\n    [1,3,0,1,0,1,3,1],\n    [1,0,0,0,0,0,0,2],\n    [1,1,1,1,1,1,1,1],\n])\n\nprint(\"Level 1:\")\nlevel1.display()" },
  { id: "gamedev-9", order: 9, title: "Save & Load Systems", description: "Persist game progress with save files.", content: "Players want to save their progress. Learn serialization, file I/O, and save slot management.", codeExample: "import json\n\nclass SaveManager:\n    def save(self, slot, data):\n        # In a real game, write to file\n        self.saved = json.dumps(data, indent=2)\n        print(f\"Saved to slot {slot}!\")\n        print(self.saved)\n\n    def load(self, slot):\n        return json.loads(self.saved)\n\n# Game state to save\ngame_state = {\n    \"player\": {\"name\": \"Hero\", \"level\": 15, \"hp\": 85, \"x\": 42, \"y\": 18},\n    \"inventory\": [\"Iron Sword\", \"Health Potion x3\", \"Gold Key\"],\n    \"quests\": {\"defeat_dragon\": False, \"find_gem\": True},\n    \"play_time\": \"2h 34m\",\n}\n\nsm = SaveManager()\nsm.save(1, game_state)\n\nloaded = sm.load(1)\nprint(f\"\\nLoaded: {loaded['player']['name']} (Level {loaded['player']['level']})\")" },
  { id: "gamedev-10", order: 10, title: "Complete Game Project", description: "Build a full game from start to finish.", content: "Combine everything you've learned into a complete, polished game with menus, levels, scoring, save/load, and enemy AI.", codeExample: "# Mini RPG - combining all concepts\nimport random\n\nclass MiniRPG:\n    def __init__(self):\n        self.hp = 100\n        self.attack = 15\n        self.gold = 0\n        self.level = 1\n        self.xp = 0\n\n    def battle(self, enemy_name, enemy_hp, enemy_atk):\n        print(f\"\\n⚔️ {enemy_name} appears! (HP:{enemy_hp})\")\n        while enemy_hp > 0 and self.hp > 0:\n            dmg = self.attack + random.randint(-3, 3)\n            enemy_hp -= dmg\n            print(f\"  You deal {dmg} damage!\")\n            if enemy_hp <= 0:\n                reward = random.randint(10, 30)\n                self.gold += reward\n                self.xp += 25\n                print(f\"  Victory! +{reward} gold, +25 XP\")\n                if self.xp >= self.level * 50:\n                    self.level += 1\n                    self.attack += 5\n                    print(f\"  🎉 LEVEL UP! Now level {self.level}\")\n                return True\n            enemy_dmg = enemy_atk + random.randint(-2, 2)\n            self.hp -= enemy_dmg\n            print(f\"  {enemy_name} deals {enemy_dmg}! (HP:{self.hp})\")\n        print(\"  💀 You were defeated...\")\n        return False\n\ngame = MiniRPG()\nenemies = [(\"Slime\", 20, 5), (\"Goblin\", 35, 8), (\"Orc\", 50, 12), (\"Dragon\", 80, 18)]\nfor name, hp, atk in enemies:\n    if not game.battle(name, hp, atk): break\nprint(f\"\\nFinal: Level {game.level}, {game.gold} gold\")" },
];

const dataEngineerLessons: PathLesson[] = [
  { id: "dataeng-1", order: 1, title: "SQL Fundamentals", description: "Query databases with SQL.", content: "SQL is the language of databases. Learn SELECT, WHERE, JOIN, GROUP BY, and ORDER BY.", codeExample: "# SQL concepts in Python (using dictionaries as tables)\nusers = [\n    {\"id\": 1, \"name\": \"Alice\", \"age\": 28, \"city\": \"NYC\"},\n    {\"id\": 2, \"name\": \"Bob\", \"age\": 34, \"city\": \"LA\"},\n    {\"id\": 3, \"name\": \"Charlie\", \"age\": 22, \"city\": \"NYC\"},\n]\n\n# SELECT * FROM users WHERE city = 'NYC'\nnyc_users = [u for u in users if u['city'] == 'NYC']\nprint(\"NYC users:\", [u['name'] for u in nyc_users])\n\n# SELECT city, COUNT(*) FROM users GROUP BY city\nfrom collections import Counter\ncities = Counter(u['city'] for u in users)\nprint(\"By city:\", dict(cities))\n\n# SELECT * FROM users ORDER BY age DESC\nsorted_users = sorted(users, key=lambda u: u['age'], reverse=True)\nprint(\"By age:\", [f\"{u['name']}({u['age']})\" for u in sorted_users])" },
  { id: "dataeng-2", order: 2, title: "APIs & Data Collection", description: "Fetch data from web APIs.", content: "Learn to collect data from REST APIs, handle JSON, and process responses.", codeExample: "# API concepts - working with JSON data\nimport json\n\n# Simulating API response\napi_response = json.dumps({\n    \"users\": [\n        {\"id\": 1, \"name\": \"Alice\", \"posts\": 42},\n        {\"id\": 2, \"name\": \"Bob\", \"posts\": 18},\n    ],\n    \"total\": 2,\n    \"page\": 1\n})\n\n# Parse and process\ndata = json.loads(api_response)\nfor user in data['users']:\n    print(f\"{user['name']}: {user['posts']} posts\")\n\nprint(f\"Total users: {data['total']}\")" },
  { id: "dataeng-3", order: 3, title: "Data Cleaning", description: "Fix messy real-world data.", content: "Real data is messy. Learn to handle missing values, fix formats, remove duplicates, and validate data.", codeExample: "# Data cleaning\nraw_data = [\n    {\"name\": \"Alice\", \"age\": \"28\", \"email\": \"alice@test.com\"},\n    {\"name\": \"Bob\", \"age\": \"\", \"email\": \"bob@test.com\"},\n    {\"name\": \"  Charlie \", \"age\": \"22\", \"email\": \"invalid\"},\n    {\"name\": \"Alice\", \"age\": \"28\", \"email\": \"alice@test.com\"},  # duplicate\n    {\"name\": \"\", \"age\": \"30\", \"email\": \"dave@test.com\"},\n]\n\ndef clean(records):\n    seen = set()\n    cleaned = []\n    for r in records:\n        r['name'] = r['name'].strip()\n        if not r['name']: continue  # skip empty names\n        r['age'] = int(r['age']) if r['age'].isdigit() else None\n        if '@' not in r['email']: r['email'] = None\n        key = (r['name'], r['email'])\n        if key in seen: continue  # skip duplicates\n        seen.add(key)\n        cleaned.append(r)\n    return cleaned\n\nresult = clean(raw_data)\nfor r in result:\n    print(r)" },
  { id: "dataeng-4", order: 4, title: "ETL Pipelines", description: "Extract, Transform, Load data workflows.", content: "ETL is the backbone of data engineering. Extract data from sources, transform it, and load it into a destination.", codeExample: "# Simple ETL pipeline\nclass Pipeline:\n    def __init__(self):\n        self.steps = []\n\n    def add_step(self, name, func):\n        self.steps.append((name, func))\n        return self\n\n    def run(self, data):\n        for name, func in self.steps:\n            print(f\"Running: {name}\")\n            data = func(data)\n            print(f\"  → {len(data)} records\")\n        return data\n\n# Build pipeline\npipeline = Pipeline()\npipeline.add_step(\"Extract\", lambda d: d)  # raw data\npipeline.add_step(\"Filter nulls\", lambda d: [r for r in d if r.get('value')])\npipeline.add_step(\"Transform\", lambda d: [{**r, 'value': r['value'] * 2} for r in d])\npipeline.add_step(\"Sort\", lambda d: sorted(d, key=lambda r: r['value'], reverse=True))\n\nraw = [{\"id\": i, \"value\": v} for i, v in enumerate([10, None, 30, None, 50, 20])]\nresult = pipeline.run(raw)\nprint(\"\\nResult:\", result)" },
  { id: "dataeng-5", order: 5, title: "Data Warehousing", description: "Design data storage for analytics.", content: "Data warehouses organize data for fast querying. Learn star schemas, fact tables, and dimension tables.", codeExample: "# Star schema concept\nclass DataWarehouse:\n    def __init__(self):\n        self.facts = []  # sales facts\n        self.products = {}  # dimension\n        self.dates = {}  # dimension\n\n    def add_product(self, id, name, category):\n        self.products[id] = {'name': name, 'category': category}\n\n    def add_sale(self, product_id, date, amount):\n        self.facts.append({'product_id': product_id, 'date': date, 'amount': amount})\n\n    def query(self, category=None):\n        results = self.facts\n        if category:\n            valid_ids = {id for id, p in self.products.items() if p['category'] == category}\n            results = [f for f in results if f['product_id'] in valid_ids]\n        total = sum(f['amount'] for f in results)\n        return {'count': len(results), 'total': total}\n\ndw = DataWarehouse()\ndw.add_product(1, 'Laptop', 'Electronics')\ndw.add_product(2, 'Phone', 'Electronics')\ndw.add_product(3, 'Book', 'Education')\ndw.add_sale(1, '2026-01', 999)\ndw.add_sale(2, '2026-01', 699)\ndw.add_sale(3, '2026-01', 29)\n\nprint('All sales:', dw.query())\nprint('Electronics:', dw.query('Electronics'))" },
  { id: "dataeng-6", order: 6, title: "Streaming Data", description: "Process real-time data streams.", content: "Not all data comes in batches. Learn to handle real-time data streams, events, and live processing.", codeExample: "import time\nimport random\n\nclass StreamProcessor:\n    def __init__(self, window_size=5):\n        self.buffer = []\n        self.window_size = window_size\n        self.alerts = []\n\n    def process(self, event):\n        self.buffer.append(event)\n        if len(self.buffer) > self.window_size:\n            self.buffer.pop(0)\n        avg = sum(e['value'] for e in self.buffer) / len(self.buffer)\n        if avg > 80:\n            self.alerts.append(f\"HIGH AVG: {avg:.1f}\")\n        return avg\n\nsp = StreamProcessor(window_size=3)\nfor i in range(8):\n    value = random.randint(50, 100)\n    event = {'timestamp': i, 'value': value}\n    avg = sp.process(event)\n    print(f\"Event {i}: value={value}, rolling_avg={avg:.1f}\")\n\nprint(f\"\\nAlerts: {sp.alerts}\")" },
  { id: "dataeng-7", order: 7, title: "Data Quality & Testing", description: "Ensure your data is accurate and reliable.", content: "Bad data = bad decisions. Learn validation rules, quality checks, and data testing frameworks.", codeExample: "class DataValidator:\n    def __init__(self):\n        self.rules = []\n        self.errors = []\n\n    def add_rule(self, name, check):\n        self.rules.append((name, check))\n\n    def validate(self, records):\n        self.errors = []\n        for i, record in enumerate(records):\n            for rule_name, check in self.rules:\n                if not check(record):\n                    self.errors.append(f\"Row {i}: Failed '{rule_name}'\")\n        return len(self.errors) == 0\n\nv = DataValidator()\nv.add_rule('name_not_empty', lambda r: bool(r.get('name', '').strip()))\nv.add_rule('age_positive', lambda r: isinstance(r.get('age'), int) and r['age'] > 0)\nv.add_rule('email_valid', lambda r: '@' in r.get('email', ''))\n\ndata = [\n    {'name': 'Alice', 'age': 28, 'email': 'alice@test.com'},\n    {'name': '', 'age': 28, 'email': 'bob@test.com'},\n    {'name': 'Charlie', 'age': -5, 'email': 'bad'},\n]\n\nvalid = v.validate(data)\nprint(f\"Valid: {valid}\")\nfor err in v.errors:\n    print(f\"  ❌ {err}\")" },
  { id: "dataeng-8", order: 8, title: "Automation & Scheduling", description: "Automate data workflows.", content: "Data pipelines need to run automatically. Learn scheduling, error handling, retries, and monitoring.", codeExample: "import time\nfrom datetime import datetime\n\nclass Scheduler:\n    def __init__(self):\n        self.jobs = []\n\n    def add_job(self, name, func, interval_sec):\n        self.jobs.append({'name': name, 'func': func, 'interval': interval_sec, 'last_run': 0, 'runs': 0})\n\n    def tick(self, current_time):\n        for job in self.jobs:\n            if current_time - job['last_run'] >= job['interval']:\n                print(f\"[{current_time}s] Running: {job['name']}\")\n                try:\n                    job['func']()\n                    job['runs'] += 1\n                    job['last_run'] = current_time\n                except Exception as e:\n                    print(f\"  ERROR: {e}\")\n\n    def report(self):\n        for job in self.jobs:\n            print(f\"  {job['name']}: ran {job['runs']} times\")\n\ns = Scheduler()\ns.add_job('Sync data', lambda: print('  Syncing...'), 2)\ns.add_job('Send report', lambda: print('  Reporting...'), 5)\n\nfor t in range(10):\n    s.tick(t)\n\nprint('\\nJob Report:')\ns.report()" },
  { id: "dataeng-9", order: 9, title: "Cloud & Deployment", description: "Deploy data systems to the cloud.", content: "Learn to deploy data pipelines on cloud platforms. Understand serverless, containers, and managed services.", codeExample: "# Cloud deployment config concept\ndeployment = {\n    'service': 'data-pipeline',\n    'runtime': 'python3.11',\n    'memory': '512MB',\n    'timeout': 300,\n    'schedule': 'every 1 hour',\n    'env': {\n        'DATABASE_URL': '${secrets.DB_URL}',\n        'API_KEY': '${secrets.API_KEY}',\n    },\n    'steps': [\n        {'name': 'extract', 'handler': 'pipeline.extract'},\n        {'name': 'transform', 'handler': 'pipeline.transform'},\n        {'name': 'load', 'handler': 'pipeline.load'},\n        {'name': 'notify', 'handler': 'pipeline.send_report'},\n    ]\n}\n\nimport json\nprint('Deployment Config:')\nprint(json.dumps(deployment, indent=2))" },
  { id: "dataeng-10", order: 10, title: "Capstone: Build a Data Platform", description: "Build a complete data engineering project.", content: "Combine everything: build an ETL pipeline that collects, cleans, stores, and reports on data.", codeExample: "# Mini Data Platform\nclass DataPlatform:\n    def __init__(self):\n        self.raw = []\n        self.cleaned = []\n        self.warehouse = {}\n\n    def ingest(self, records):\n        self.raw.extend(records)\n        print(f'Ingested {len(records)} records')\n\n    def clean(self):\n        self.cleaned = [r for r in self.raw if all(r.values())]\n        print(f'Cleaned: {len(self.raw)} → {len(self.cleaned)}')\n\n    def aggregate(self):\n        for r in self.cleaned:\n            cat = r['category']\n            if cat not in self.warehouse:\n                self.warehouse[cat] = {'count': 0, 'total': 0}\n            self.warehouse[cat]['count'] += 1\n            self.warehouse[cat]['total'] += r['amount']\n\n    def report(self):\n        print('\\n📊 Report:')\n        for cat, stats in self.warehouse.items():\n            avg = stats['total'] / stats['count']\n            print(f'  {cat}: {stats[\"count\"]} sales, ${stats[\"total\"]:.0f} total, ${avg:.0f} avg')\n\nplatform = DataPlatform()\nplatform.ingest([\n    {'category': 'Tech', 'amount': 999, 'region': 'US'},\n    {'category': 'Tech', 'amount': 499, 'region': 'EU'},\n    {'category': 'Books', 'amount': 29, 'region': 'US'},\n    {'category': 'Books', 'amount': None, 'region': 'US'},\n    {'category': 'Tech', 'amount': 799, 'region': 'US'},\n])\nplatform.clean()\nplatform.aggregate()\nplatform.report()" },
];

const mobileDevLessons: PathLesson[] = Array.from({ length: 10 }, (_, i) => ({
  id: `mobile-${i + 1}`,
  order: i + 1,
  title: ["React Native Setup", "Components & Styling", "Navigation & Routing", "State Management", "API Integration", "Local Storage", "Push Notifications", "App Performance", "App Store Publishing", "Capstone: Build a Mobile App"][i],
  description: ["Set up your React Native development environment.", "Build mobile UI components.", "Navigate between screens.", "Manage app state with hooks and context.", "Connect to APIs and handle data.", "Store data locally on the device.", "Send and receive push notifications.", "Optimize your app for speed.", "Publish to the App Store and Google Play.", "Build a complete mobile application."][i],
  content: `This lesson covers ${["React Native Setup", "Components & Styling", "Navigation", "State Management", "APIs", "Local Storage", "Push Notifications", "Performance", "Publishing", "Complete App"][i]} for mobile development with React Native.\n\n**What you'll learn:**\n- Core mobile development concepts\n- React Native specific patterns\n- Platform differences (iOS vs Android)\n- Best practices for mobile UX`,
  codeExample: `// React Native - ${["Setup", "Components", "Navigation", "State", "API", "Storage", "Notifications", "Performance", "Publishing", "Full App"][i]}\nimport React from 'react';\nimport { View, Text, StyleSheet } from 'react-native';\n\nexport default function App() {\n    return (\n        <View style={styles.container}>\n            <Text style={styles.title}>Mobile App</Text>\n        </View>\n    );\n}\n\nconst styles = StyleSheet.create({\n    container: { flex: 1, justifyContent: 'center', alignItems: 'center' },\n    title: { fontSize: 24, fontWeight: 'bold' },\n});`,
}));

// ==================== ADVANCED LESSONS ====================

const advancedPythonTitles = [
  "Metaclasses Deep Dive", "Descriptors & Protocols", "Async Generators & Streams",
  "C Extensions with ctypes", "Memory Profiling & Optimization", "Custom Decorators Framework",
  "Building a Web Framework", "Compiler Design Basics", "Distributed Systems with Python",
  "Kubernetes & Docker for Python", "GraphQL Server Implementation", "Real-Time WebSockets",
  "Security & Cryptography", "Building a Package Manager", "Contributing to Open Source",
  "System Design Patterns", "High-Performance Computing", "Building a Database Engine",
  "ML Model Deployment (MLOps)", "Staff Engineer Best Practices",
];

const advancedJsTitles = [
  "V8 Engine Internals", "WebAssembly Integration", "Custom Bundler Design",
  "Micro-Frontend Architecture", "Real-Time Collaboration (CRDT)", "Browser Extension Development",
  "WebGL & 3D Graphics", "Service Worker Advanced Patterns", "Custom React Renderer",
  "Compiler/Transpiler Design", "GraphQL Subscriptions", "Edge Computing with Workers",
  "Security Hardening", "Monorepo Architecture", "Contributing to Open Source",
  "System Design for Frontend", "Performance Engineering", "Building a JS Runtime",
  "Full-Stack TypeScript Patterns", "Principal Engineer Best Practices",
];

// ==================== EXPORT ALL PATHS ====================

export const SPECIALIZATION_PATHS: SpecializationPath[] = [
  {
    id: "web-designer", name: "Web Designer", icon: "🎨", color: "pink",
    language: "javascript", description: "Design and build beautiful, responsive websites from scratch.",
    prerequisite: "js-100",
    lessons: webDesignerLessons,
    capstoneTitle: "Build a Complete Portfolio Website",
    capstoneDescription: "Design and build a professional portfolio website with responsive layout, animations, dark mode, and multiple pages.",
    capstoneRequirements: ["Responsive design (mobile + desktop)", "At least 4 pages", "CSS animations and transitions", "Contact form", "Project gallery with filters", "Dark/light mode toggle"],
    certificateName: "Certified Web Designer",
  },
  {
    id: "ai-ml", name: "AI & Machine Learning", icon: "🤖", color: "purple",
    language: "python", description: "Build intelligent systems that learn from data.",
    prerequisite: "python-100",
    lessons: aiPathLessons,
    capstoneTitle: "Build Your Own AI System",
    capstoneDescription: "Create a complete AI application that collects data, trains a model, makes predictions, and serves results via an API.",
    capstoneRequirements: ["Data collection and preprocessing", "Model training with evaluation", "Prediction API endpoint", "At least 80% accuracy on test data", "Save/load trained model", "User-friendly interface"],
    certificateName: "Certified AI Developer",
  },
  {
    id: "game-dev", name: "Game Developer", icon: "🎮", color: "green",
    language: "python", description: "Create games with physics, AI enemies, and progression systems.",
    prerequisite: "python-100",
    lessons: gameDevLessons,
    capstoneTitle: "Build a Complete RPG Game",
    capstoneDescription: "Create a text-based RPG with combat, inventory, quests, multiple levels, save/load, and enemy AI.",
    capstoneRequirements: ["Character creation and stats", "Turn-based combat system", "Inventory and items", "At least 3 levels/areas", "Save and load game", "Enemy AI with different behaviors", "Score and leaderboard"],
    certificateName: "Certified Game Developer",
  },
  {
    id: "data-engineer", name: "Data Engineer", icon: "📊", color: "blue",
    language: "python", description: "Build data pipelines, warehouses, and analytics systems.",
    prerequisite: "python-100",
    lessons: dataEngineerLessons,
    capstoneTitle: "Build a Data Platform",
    capstoneDescription: "Create a complete data platform with ETL pipelines, a data warehouse, automated scheduling, and a reporting dashboard.",
    capstoneRequirements: ["ETL pipeline with 3+ sources", "Data cleaning and validation", "Aggregated data warehouse", "Automated scheduling", "Error handling and logging", "Dashboard with key metrics"],
    certificateName: "Certified Data Engineer",
  },
  {
    id: "mobile-dev", name: "Mobile App Developer", icon: "📱", color: "cyan",
    language: "javascript", description: "Build cross-platform mobile apps with React Native.",
    prerequisite: "js-100",
    lessons: mobileDevLessons,
    capstoneTitle: "Build a Mobile App",
    capstoneDescription: "Create a complete mobile application with navigation, data persistence, API integration, and app store readiness.",
    capstoneRequirements: ["Multiple screens with navigation", "State management", "API integration", "Local data storage", "Clean UI with animations", "App icon and splash screen"],
    certificateName: "Certified Mobile Developer",
  },
];

export const ADVANCED_PYTHON: { id: string; title: string; description: string }[] = advancedPythonTitles.map((title, i) => ({
  id: `adv-python-${i + 1}`,
  title,
  description: `Advanced Python: ${title}. High-skill lesson for experienced developers.`,
}));

export const ADVANCED_JS: { id: string; title: string; description: string }[] = advancedJsTitles.map((title, i) => ({
  id: `adv-js-${i + 1}`,
  title,
  description: `Advanced JavaScript: ${title}. High-skill lesson for experienced developers.`,
}));

export function getPathById(id: string): SpecializationPath | undefined {
  return SPECIALIZATION_PATHS.find((p) => p.id === id);
}
